[package]
name = "rc_car_camera_server"
version = "0.1.0"
edition = "2024"

[dependencies]
maf = { path = "../maf/crates/maf" }
anyhow = "^1.0.96"
serde = "^1"
thiserror = "2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[lib]
crate-type = ["cdylib"]
